/** Plain-language explanations for every important metric (used in tooltips). */
export const TIPS = {
  implementationPrice: 'One-time selling price for discovery, build, integration, testing, deployment and change management. Price = implementation delivery cost ÷ (1 − implementation margin).',
  monthlyCost: 'Total monthly delivery cost = AI consumption + infrastructure & platform + AgentOps + human review & other attributable costs. Includes failed executions and retries.',
  costPerAbu: 'Fully loaded monthly delivery cost ÷ accepted weighted ABUs. The cost of failed attempts and retries is carried by the accepted outcomes.',
  abuPrice: 'Recommended price per ABU = cost per ABU ÷ (1 − target margin). If AgentOps is billed as a separate fee, its cost is excluded here so it is never recovered twice.',
  acuPrice: 'Recommended price per ACU = fully loaded cost per ACU ÷ (1 − target margin). An ACU is a normalised unit of AI consumption — not a token.',
  monthlyCharge: 'What the client is invoiced each month in year 1 under the selected commercial model (excludes the one-time implementation fee).',
  grossMargin: 'Provider gross margin on recurring revenue = (monthly revenue − monthly delivery cost) ÷ monthly revenue.',
  acu: 'AI Consumption Unit: a normalised measure of AI technical consumption (tokens, OCR, tools, orchestration). Configured in Settings by cost normalisation or weighted resources.',
  abu: 'AI Business Unit: one accepted unit of business work (e.g. a processed invoice), weighted by complexity. Each unique transaction counts once, however many retries it took.',
  weightedAbus: 'Accepted unique transactions × complexity weight (default Low 1.0, Medium 1.5, High 3.0).',
  failureCost: 'Part of the monthly cost spent on executions that did not end in an accepted outcome (failures, retries, duplicates). It is already inside the total and is allocated to accepted ABUs.',
  capacityValue: 'Hours saved × loaded employee cost. This is productivity (redeployable capacity), not cash — it only becomes a saving when spend actually falls.',
  hardSavings: 'The share of capacity value the client converts into an actual reduction in spend (e.g. reduced contractor or outsourcing cost).',
  financialBenefit: 'Hard savings + cost avoidance + attributable revenue margin. Each item is marked as an assumption or a validated actual.',
  roi: 'ROI = (financial benefits − total AI investment) ÷ total AI investment × 100. Investment = implementation price + all recurring client charges.',
  roiValidated: 'ROI counting only benefits marked as validated. Use this figure for commitments; the business-case ROI includes assumptions.',
  payback: 'Months to recover the implementation price from monthly net benefit (financial benefit − monthly client charge).',
  annualRevenue: 'Year-1 revenue = implementation price + 12 × monthly recurring revenue.',
  tcv: 'Total contract value: revenue over the full contract term, including annual escalation and volume growth.',
  agentOps: 'Run-the-agent services: monitoring, incident management, L1/L2/L3 support, evaluation, optimisation, release management and governance reporting.',
  recovery: 'Each cost pool is assigned to exactly one revenue component (or passed through to the client, or carried at risk under gainshare). This prevents the same cost being recovered twice.',
  productivity: 'Hours saved ÷ current manual hours. Transactions the agent does not complete fall back to fully manual handling.',
  fte: 'Hours saved ÷ productive hours per FTE per month (Settings). Capacity that can be redeployed — not headcount reduction unless the client decides so.',
};
